from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, field_validator, model_validator


class CameraFlow(str, Enum):
    """Camera movement pattern that determines how frames are composed within a shot."""

    WIDE_TO_CLOSE = "wide_to_close"      # establishing → detail (dialogue/narrative)
    CLOSE_TO_WIDE = "close_to_wide"      # detail → reveal (twist, revelation)
    PAN_ACROSS = "pan_across"            # same zoom, different region (action/fight)
    DETAIL_REVEAL = "detail_reveal"      # extreme close-up → medium (horror/mystery)
    STATIC_CLOSE = "static_close"        # single close-up frame (hook shots ≤3s)
    STATIC_WIDE = "static_wide"          # single wide frame (establishing scene-only)


class MotionDirection(str, Enum):
    """Ken Burns motion direction for a single frame's zoompan effect."""

    ZOOM_IN = "zoom_in"
    ZOOM_OUT = "zoom_out"
    PAN_LEFT = "pan_left"
    PAN_RIGHT = "pan_right"
    PAN_UP = "pan_up"
    PAN_DOWN = "pan_down"


class ShotSubject(str, Enum):
    """What is the VISUAL HERO of the shot.

    Drives framing (extreme close-up vs wide), camera flow, and whether characters
    are rendered with IPAdapter identity at all. Non-person subjects make the shot
    "shock-forward" (corpse face, wound, blood, ghost) which is the retention lever
    for horror shorts.
    """

    PERSON_ACTION = "person_action"            # default — character performing action
    CORPSE_FACE = "corpse_face"                # extreme close-up pale dead face / eyes
    WOUND = "wound"                            # macro bite mark / gash / blood wound
    BLOODY_OBJECT = "bloody_object"            # blood-soaked dagger/talisman/cloth
    SUPERNATURAL_ENTITY = "supernatural_entity"  # ghost, spirit, possessed form
    RITUAL_OBJECT = "ritual_object"            # glowing talisman, candles, altar
    ENVIRONMENT = "environment"                # pure atmosphere, no human focus


class EnergyLevel(str, Enum):
    """Perceived attention/tension level of a shot.

    Used by the constraint validator to detect monotony (3+ consecutive same level)
    and to drive frame_decomposer choices (SHOCK → close-up frame 0). Inferred from
    shot_subject + camera_flow + duration + narration keywords by
    `llm.constraint_validator.infer_energy_level`. Field is `Optional[None]` on
    `Optional[EnergyLevel]` on `ShotScript` until populated; `None` means "not yet computed".
    """

    LOW = "low"        # ambient / establishing
    MED = "med"        # normal dialogue or action
    HIGH = "high"      # impactful action or revelation
    SHOCK = "shock"    # extreme close-up / gore / supernatural reveal


class HookCandidate(BaseModel):
    """A single hook variant produced by the multi-candidate hook generator.

    Persisted alongside scores to `data/{slug}/hook_candidates/episode-NNN.json`
    so Phase 6 calibration can compare judge winners vs hand-rated winners.
    """

    text: str                                   # narration ≤10 words, Vietnamese
    visual_seed: str                            # scene_prompt skeleton
    curiosity_score: float = 0.0                # 0-1, from hook_judge rubric
    specificity_score: float = 0.0              # 0-1
    pattern_interrupt_score: float = 0.0        # 0-1
    total_score: float = 0.0                    # weighted sum (config-driven weights)
    rationale: str = ""                         # why this candidate scored this way


class ViralMoment(BaseModel):
    """A "viral moment" candidate extracted from chapter content.

    Drives only the hook + at most 1-2 key shots. The narrative spine of the
    episode still comes from `ArcOverview` (faithful summary). Lets the hook
    extractor "drop context" for shock value without lopsiding the whole script.
    """

    chapter_refs: List[int]   # source chapter numbers
    description: str          # short summary of the moment
    shock_factor: str         # what makes it shocking/curiosity-inducing
    mystery_seed: str         # the unanswered question to seed in the hook


class FrameScript(BaseModel):
    """A single frame within a shot — generated by frame_decomposer, not LLM."""

    scene_prompt: str                   # scene_prompt with camera_tag prepended
    camera_tag: str                     # e.g. "wide establishing shot", "close-up shot"
    motion: MotionDirection = MotionDirection.ZOOM_IN


class ShotVisualBrief(BaseModel):
    """Structured visual description extracted by LLM from narration_text.

    Used as an intermediate representation before synthesis into a ComfyUI
    tag list. LLM only does extraction here; Python handles formatting.
    """

    subjects: List[str]        # role tags, max 2, no character names (e.g. "hooded daoist figure")
    actions: List[str] = []    # 1-3 micro-events in timeline order; actions[i] maps to frame[i]
    setting: str               # physical location with visual detail
    key_objects: List[str]     # foreground props, max 4
    mood_lighting: str         # "light source + color palette + effect" format
    composition: str = ""      # camera framing tag; empty → mapped from camera_flow
    shot_subject: ShotSubject = ShotSubject.PERSON_ACTION  # visual hero; drives framing

    @field_validator("actions", mode="before")
    @classmethod
    def coerce_action_string(cls, v: object) -> List[str]:
        """Backward compat: accept legacy single-string 'action' passed as the value."""
        if isinstance(v, str):
            return [v] if v.strip() else []
        return v if isinstance(v, list) else []


class ShotScript(BaseModel):
    """Schema for a single shot in an episode script."""

    scene_prompt: str          # English, for ComfyUI
    narration_text: str        # Vietnamese, for TTS
    duration_sec: float = 6.0
    is_key_shot: bool = False
    characters: List[str] = []  # [] = scene-only shot, no IPAdapter
    characters_raw: Optional[List[str]] = None  # raw LLM list before Phase 1 resolution; debug only
    camera_flow: CameraFlow = CameraFlow.WIDE_TO_CLOSE
    frames: List[FrameScript] = []  # populated by frame_decomposer, not LLM
    scene_id: Optional[str] = None  # shared across shots in the same physical location, e.g. "coffin_shop"
    actual_audio_sec: Optional[float] = None  # probed from mixed audio file; used for subtitle timing only
    visual_brief: Optional[ShotVisualBrief] = None  # None for old scripts → synthesis skipped
    shot_subject: ShotSubject = ShotSubject.PERSON_ACTION  # visual hero; non-person → no IPAdapter

    # Constraint-system fields (auto-derived by constraint_validator).
    # `None` = not yet computed (sentinel). Validator backfills on first read.
    energy_level: Optional[EnergyLevel] = None
    proper_nouns: Optional[List[str]] = None    # union of characters + lore_terms detected in narration
    exposition_ratio: Optional[float] = None    # 0-1; fraction of expository sentences


class EpisodeScript(BaseModel):
    """Full script for one episode (8-10 shots)."""

    episode_num: int
    title: str
    shots: List[ShotScript]

    # Constraint-system fields.
    hook_strength: Optional[float] = None         # winning hook total_score from hook_judge
    constraint_violations: List[str] = []         # rule violations that survived gatekeeper retries
    prompt_version: str = "v1"                    # "v1" = legacy scriptwriter; "v2" = constraint-system

    @model_validator(mode="after")
    def warn_shot_count(self) -> "EpisodeScript":
        n = len(self.shots)
        if not (8 <= n <= 10):
            # Script writer will normalize, just validate it's reasonable
            if n < 1 or n > 20:
                raise ValueError(f"shots count {n} is out of acceptable range [1, 20]")
        return self


class Character(BaseModel):
    """Character profile for ComfyUI image generation."""

    name: str
    alias: List[str] = []
    gender: str = "male"       # "male" | "female"
    description: str           # English appearance description for ComfyUI
    relationships: dict = {}   # { other_character_name: relationship_description }
    anchor_path: Optional[str] = None


class ChapterMeta(BaseModel):
    """Metadata and content for a single crawled chapter."""

    chapter_num: int
    title: str
    url: str
    content: Optional[str] = None
    status: str = "PENDING"    # PENDING | CRAWLED | ERROR
    crawled_at: Optional[datetime] = None
    error_msg: Optional[str] = None


class ChunkSummary(BaseModel):
    """Pass-1 summary for a group of chapters within one episode."""

    episode_num: int
    chunk_index: int
    chapter_start: int
    chapter_end: int
    summary: str


class ArcOverview(BaseModel):
    """Pass-2 arc synthesis for a full episode."""

    episode_num: int
    arc_summary: str
    key_events: List[str]
    characters_in_episode: List[str]
